//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Home:public drogon::DrTemplate<Home>
{
public:
	Home(){};
	virtual ~Home(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
