//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Home.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Home::genText(const DrTemplateData& Home_view_data)
{
	drogon::OStringStream Home_tmp_stream;
	std::string layoutName{""};
	Home_tmp_stream << "<!DOCTYPE html>\n";
	Home_tmp_stream << "<html>\n";
	Home_tmp_stream << "<head>\n";
	Home_tmp_stream << "    ";
        auto posts=Home_view_data.get<std::unordered_map<std::string,std::string>>("posts");
    
	Home_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	Home_tmp_stream << "    <title>Hello!</title>\n";
	Home_tmp_stream << "</head>\n";
	Home_tmp_stream << "<body>\n";
	Home_tmp_stream << "    <h1>";
{
    auto & val=Home_view_data["posts"];
    if(val.type()==typeid(const char *)){
        Home_tmp_stream<<*any_cast<const char *>(&val);
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        Home_tmp_stream<<*any_cast<const std::string>(&val);
    }
}
	Home_tmp_stream << "</h1>\n";
	Home_tmp_stream << "</body>\n";
if(layoutName.empty())
{
std::string ret{std::move(Home_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Home_view_data;
auto str = std::move(Home_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
